yaml
name: Global Image Optimization
on:
  push:
    branches:
      - main  # Make sure this matches your primary branch name
    paths:
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Compress Images
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          # This ensures the bot doesn't ruin the quality
          jpegQuality: '80'
          pngQuality: '80'
          webpQuality: '80'
          ignorePaths: 'node_modules/**'
